import Head from 'next/head';
import Image from 'next/image';
import { Roboto } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { RuxClock } from '@astrouxds/react';
import { Table } from '@/components/Table';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-full grid grid-cols-1 grid-rows-2 md:grid-cols-2 md:grid-rows-1 gap-4 p-4">
          <Table />
          <Table withDiv />
        </div>
      </main>
    </>
  );
}
